analytics: {}
color:
  brandColors:
    - '#C0C0B8'
    - '#000000'
    - '#888880'
    - '#000000'
    - '#000000'
  brandStrength: 1
  lightness: 1
  rhythmicContrast: 0.516892
  saturation: 0.498311
cta: {}
layout_spectrum: 0.9885510937116135
name: Blox
opengraph: {}
purpose: {}
typography_spectrum: 0.208615
